# The URL the site will be built for
base_url = "https://we-do.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "fr"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[languages.fr]
title = "Weber Douglas Development"

[languages.en]
title = "Weber Douglas Development"

[languages.en.translations]
name = "English"
imprint = "Imprint"
privacy-policy = "Privacy Policy"
phone = "Phone"

[languages.de]
title = "Weber Douglas Development"

[languages.de.translations]
name = "Deutsch"
imprint = "Impressum"
privacy-policy = "Datenschutzerklärung"
phone = "Telefon"

[extra]
email = "welcome@we-do.dev"
phone_disp = "+49 (0) 177 2480821"
home_element = { path = "/", title = "Home" }

[extra.company]
name = "Weber Douglas Development"
address_l1 = "Durlacher Str. 23"
address_l2 = "76275 Ettlingen"
email_privacy = "privacy@we-do.dev"
phone_disp = "+49 (0) 177 2480821"
